@devhost=http://localhost:5000
@cookie=auth_name=Spring;auth_token=6s2y463m5t30667605s

## About user

###
POST {{devhost}}/api/login
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "Spring",
    "password": "123456"
}


###
POST {{devhost}}/api/logout
Cookie: {{cookie}}

###
GET {{devhost}}/api/user/info
Cookie: {{cookie}}

# About Group
###
GET {{devhost}}/api/group
Cookie: {{cookie}}

###
POST {{devhost}}/api/group
Cookie: {{cookie}}
Content-Type: application/json

{
    "name": "Group-Z",
    "intro": "intro"
}

###
GET {{devhost}}/api/group/name
Cookie: {{cookie}}

# About Application
### 
GET {{devhost}}/api/application
Cookie: {{cookie}}


###
GET {{devhost}}/api/application/name?groupId=1
Cookie: {{cookie}}


###
POST {{devhost}}/api/application
Content-Type: application/json
Cookie: {{cookie}}

{
    "name": "producer-server",
    "intro": "商家服务, 提供商家相关接口",
    "groupId": 4

}

###
DELETE {{devhost}}/api/application/8
Cookie: {{cookie}}

### About protobuf
GET {{devhost}}/api/protobuf?search=order-server
Cookie: {{cookie}}

###
GET {{devhost}}/api/protobuf
Cookie: {{cookie}}

###
GET {{devhost}}/api/protobuf/1
Cookie: {{cookie}}

###
POST {{devhost}}/api/protobuf
Content-Type: application/json
Cookie: {{cookie}}

{
    "applicationId": 2,
    "name": "producer_service",
    "intro": "商家服务rpc接口",
    "protocol": "grpc"
}

###
PUT {{devhost}}/api/protobuf/1/intro
Content-Type: application/json
Cookie: {{cookie}}

{
    "intro": "订单服务rpc接口的描述"
}

###
PUT {{devhost}}/api/protobuf/3/current-version
Content-Type: application/json
Cookie: {{cookie}}

{
    "version": 102
}

###
DELETE {{devhost}}/api/protobuf/3
Cookie: {{cookie}}

###
GET {{devhost}}/api/protobuf/1/current-code
Cookie: {{cookie}}


###
POST {{devhost}}/api/protobuf/code
Content-Type: application/json
Cookie: {{cookie}}

{
    "protoId": 1,
    "code": "code...",
    "creator": "onemsg"
}

###
GET {{devhost}}/api/protobuf/code/1
Cookie: {{cookie}}

###
GET {{devhost}}/api/protobuf/1/code
Cookie: {{cookie}}

###
GET {{devhost}}/sleep?time=1000
Cookie: {{cookie}}

###
GET {{devhost}}/test-null

###
GET {{devhost}}/test-null-html
# Accept: text/html

###
GET {{devhost}}/error

###
GET {{devhost}}/test-exception

###
GET {{devhost}}/test-exception
Accept: text/html

###
GET  {{devhost}}/404
